server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
spring:
  application:onf
    name: delivery_web
  mvc:
    static-path-pattern: /**
  data:
    mongodb:
      database: test
      host: 192.168.10.128
      port: 27017
redis:
  host: 127.0.0.1
  maxActive: 600
  maxIdle: 300
  maxWait: 1000
  pass: ''
  port: 6379
  testOnBorrow: true
feign:
  hystrix:
    enabled: true